version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data

  presentationapi:
    image: ${DOCKER_REGISTRY-}presentationapi
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: PresentationApi/Dockerfile

  transferworker:
    image: ${DOCKER_REGISTRY-}transferworker
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    build:
      context: .
      dockerfile: TransferWorker/Dockerfile

  auditlogworker:
    image: ${DOCKER_REGISTRY-}auditlogworker
    restart: always
    build:
      context: .
      dockerfile: AuditLogWorker/Dockerfile

volumes:
  postgres:
    driver: local